In [1]:
import tensorflow as tf 
import numpy as np
import pickle
import cv2

In [3]:
cap = cv2.VideoCapture(0)
print("Press 'q' to exit")
while True:
    ret, frame = cap.read()
    cv2.imshow('Macbook_Cam0', frame)
    img = frame
    print(frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

Press 'q' to exit
[[[ 46  56  32]
  [ 36  47  22]
  [ 31  33  14]
  ...
  [224 255 249]
  [227 255 252]
  [227 255 252]]

 [[ 50  61  36]
  [ 45  55  31]
  [ 37  38  20]
  ...
  [224 255 249]
  [227 255 252]
  [227 255 252]]

 [[ 59  72  40]
  [ 52  65  33]
  [ 47  53  22]
  ...
  [224 255 249]
  [226 255 249]
  [227 255 250]]

 ...

 [[ 60  79  56]
  [ 60  79  56]
  [ 60  78  57]
  ...
  [ 49  56   0]
  [ 47  56   2]
  [ 45  54   1]]

 [[ 60  78  57]
  [ 59  77  56]
  [ 60  78  59]
  ...
  [ 49  57   0]
  [ 49  57   0]
  [ 47  56   0]]

 [[ 61  80  58]
  [ 60  78  57]
  [ 60  78  59]
  ...
  [ 49  57   0]
  [ 47  56   0]
  [ 47  56   0]]]
[[[118 107 118]
  [106  96 107]
  [ 81  68  86]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[135 125 136]
  [123 112 123]
  [106  93 111]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[160 154 158]
  [150 144 147]
  [136 126 137]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[156 165 150]
  [156 165 150]
  

[[[113 112 123]
  [ 92  91 102]
  [ 73  69  86]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[144 142 154]
  [117 115 127]
  [105 102 118]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[184 187 186]
  [151 153 153]
  [132 132 139]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[169 171 157]
  [169 171 157]
  [172 174 162]
  ...
  [125 108  56]
  [119 107  56]
  [119 107  56]]

 [[169 171 157]
  [167 170 156]
  [169 171 157]
  ...
  [123 108  53]
  [120 106  54]
  [120 106  54]]

 [[169 171 157]
  [169 171 157]
  [170 172 158]
  ...
  [123 108  53]
  [118 104  51]
  [119 105  53]]]
[[[138 138 131]
  [ 85  85  78]
  [ 66  58  68]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[153 153 147]
  [116 116 109]
  [ 93  84  95]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[182 187 172]
  [150 155 141]
  [127 123 122]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[171 173 168]
  [172 174 169]
  [174 178 173]
  ..

[[[132 131 133]
  [128 127 130]
  [ 62  57  71]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[168 167 169]
  [141 140 143]
  [113 108 123]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[184 194 172]
  [170 180 158]
  [134 132 137]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[174 177 163]
  [176 178 164]
  [176 176 163]
  ...
  [123 108  53]
  [121 108  58]
  [119 107  56]]

 [[172 176 164]
  [175 179 167]
  [177 178 167]
  ...
  [123 108  53]
  [121 108  58]
  [121 108  58]]

 [[171 175 163]
  [172 176 164]
  [174 176 164]
  ...
  [125 109  54]
  [121 108  58]
  [121 108  58]]]
[[[109 105  96]
  [ 74  70  61]
  [ 47  42  45]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[176 172 164]
  [111 107  98]
  [ 62  57  60]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[206 210 191]
  [179 183 164]
  [108 102  94]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[174 178 161]
  [174 178 161]
  [172 174 160]
  ..

[[[132 132 127]
  [102 101  97]
  [ 63  55  67]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[174 174 169]
  [139 139 134]
  [120 112 124]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[184 190 173]
  [168 173 157]
  [156 149 143]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[171 173 159]
  [170 172 158]
  [169 170 159]
  ...
  [123 108  52]
  [118 106  54]
  [118 106  54]]

 [[169 172 162]
  [168 171 161]
  [167 170 160]
  ...
  [123 108  52]
  [119 108  55]
  [118 106  54]]

 [[168 171 161]
  [167 170 160]
  [167 170 160]
  ...
  [125 110  53]
  [119 108  55]
  [116 104  51]]]
[[[133 129 128]
  [ 91  87  86]
  [ 52  47  55]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[164 160 158]
  [136 132 130]
  [101  96 104]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[181 185 173]
  [160 164 152]
  [133 130 126]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[168 170 151]
  [168 170 151]
  [168 170 151]
  ..

[[[152 148 153]
  [ 80  76  81]
  [ 32  26  38]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[179 175 180]
  [151 147 152]
  [ 77  70  83]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[187 190 183]
  [178 181 173]
  [146 145 143]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[173 173 159]
  [173 173 159]
  [173 172 161]
  ...
  [118 105  48]
  [114 104  51]
  [114 104  51]]

 [[176 173 162]
  [175 172 161]
  [173 172 161]
  ...
  [118 106  47]
  [113 104  49]
  [112 103  47]]

 [[176 173 162]
  [175 172 161]
  [174 173 162]
  ...
  [118 106  47]
  [112 103  47]
  [110 102  46]]]
[[[124 121 124]
  [108 105 108]
  [ 70  66  78]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[165 162 165]
  [138 135 138]
  [113 109 121]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[187 190 176]
  [176 178 164]
  [143 140 143]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[168 168 147]
  [169 169 149]
  [170 170 151]
  ..

[[[134 137 136]
  [ 84  87  86]
  [ 57  54  63]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[158 160 160]
  [120 123 122]
  [ 80  77  87]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[174 179 171]
  [153 158 150]
  [133 133 133]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[178 178 164]
  [178 178 164]
  [178 178 164]
  ...
  [128 110  63]
  [123 106  61]
  [119 102  57]]

 [[181 178 167]
  [180 176 166]
  [181 178 167]
  ...
  [128 111  61]
  [123 107  59]
  [120 104  57]]

 [[181 178 167]
  [181 178 167]
  [180 176 166]
  ...
  [122 105  55]
  [119 103  56]
  [117 101  53]]]
[[[150 148 146]
  [130 129 127]
  [ 68  61  69]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[163 161 159]
  [156 154 152]
  [130 123 131]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[167 176 170]
  [156 165 159]
  [151 149 156]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[169 175 165]
  [168 174 164]
  [164 171 159]
  ..

[[[151 147 152]
  [100  96 101]
  [ 95  92 106]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[192 188 193]
  [142 138 143]
  [ 98  96 110]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[216 221 211]
  [176 182 172]
  [131 131 138]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[218 223 208]
  [218 223 208]
  [218 223 208]
  ...
  [172 154  91]
  [171 152  92]
  [167 149  88]]

 [[215 220 206]
  [217 221 207]
  [217 221 207]
  ...
  [171 153  86]
  [172 154  91]
  [171 153  90]]

 [[215 220 206]
  [215 220 206]
  [217 221 207]
  ...
  [169 151  83]
  [169 152  89]
  [169 152  89]]]
[[[160 154 158]
  [102  96  99]
  [ 78  73  88]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[189 184 187]
  [137 131 134]
  [ 82  77  91]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[205 207 193]
  [188 191 177]
  [124 121 124]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[216 227 209]
  [215 225 208]
  [215 225 208]
  ..

[[[203 202 200]
  [172 170 168]
  [139 135 145]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[215 214 212]
  [200 198 196]
  [177 174 183]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[228 231 223]
  [214 217 209]
  [200 198 198]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[217 221 207]
  [217 221 207]
  [215 219 207]
  ...
  [171 155  82]
  [170 156  88]
  [169 155  87]]

 [[217 220 206]
  [217 220 206]
  [216 218 206]
  ...
  [171 156  81]
  [169 156  85]
  [167 155  84]]

 [[216 219 205]
  [215 218 204]
  [214 216 204]
  ...
  [171 156  81]
  [167 155  84]
  [166 154  83]]]
[[[199 202 194]
  [182 184 177]
  [140 138 143]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[214 217 209]
  [194 197 190]
  [170 168 173]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[231 238 223]
  [205 213 198]
  [192 192 192]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[217 220 210]
  [217 220 210]
  [217 220 210]
  ..

[[[162 159 160]
  [118 116 116]
  [ 86  84  98]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[203 201 201]
  [157 154 155]
  [105 103 117]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[230 230 216]
  [204 204 191]
  [160 158 158]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[218 227 207]
  [217 226 206]
  [216 225 205]
  ...
  [165 155  84]
  [163 154  87]
  [161 152  85]]

 [[217 226 206]
  [216 225 205]
  [216 225 205]
  ...
  [164 151  81]
  [161 150  81]
  [158 147  79]]

 [[217 226 206]
  [216 225 205]
  [215 224 204]
  ...
  [163 150  79]
  [158 147  79]
  [156 145  76]]]
[[[170 171 160]
  [118 120 108]
  [ 88  83  77]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[195 197 185]
  [160 162 150]
  [118 113 107]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[218 222 210]
  [196 200 188]
  [165 162 156]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[213 217 205]
  [214 218 206]
  [214 218 206]
  ..

[[[199 197 195]
  [186 184 182]
  [112 109 109]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[213 211 209]
  [194 193 191]
  [169 166 167]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[236 235 231]
  [207 206 202]
  [194 192 192]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[223 223 209]
  [222 222 208]
  [218 219 203]
  ...
  [171 153  90]
  [167 151  92]
  [165 148  90]]

 [[219 220 204]
  [218 219 203]
  [217 218 202]
  ...
  [171 153  90]
  [169 152  93]
  [166 150  91]]

 [[217 218 202]
  [216 217 201]
  [216 217 201]
  ...
  [172 154  91]
  [170 153  94]
  [169 152  93]]]
[[[188 188 182]
  [167 167 161]
  [105 100 107]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[206 206 199]
  [186 186 179]
  [155 150 157]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[222 224 212]
  [210 212 200]
  [185 182 183]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[217 222 205]
  [217 222 205]
  [215 221 204]
  ..

[[[153 153 153]
  [126 126 126]
  [ 87  81  91]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[174 174 174]
  [144 144 144]
  [127 121 131]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[204 208 196]
  [174 178 166]
  [159 156 152]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[215 221 204]
  [215 221 204]
  [215 221 204]
  ...
  [172 154  91]
  [167 152  90]
  [163 147  86]]

 [[216 220 203]
  [216 220 203]
  [216 220 203]
  ...
  [175 158  95]
  [171 156  92]
  [166 151  88]]

 [[215 218 202]
  [215 218 202]
  [214 217 201]
  ...
  [175 158  95]
  [172 157  93]
  [170 155  91]]]
[[[160 170 166]
  [127 137 133]
  [102 104 111]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[193 204 200]
  [155 165 161]
  [118 121 127]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[205 224 207]
  [186 205 188]
  [151 155 156]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[216 220 203]
  [215 218 202]
  [211 216 200]
  ..

[[[149 151 153]
  [ 78  80  82]
  [ 60  65  71]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[190 192 194]
  [140 142 144]
  [ 74  79  85]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[206 210 198]
  [183 187 175]
  [132 136 138]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[217 224 209]
  [217 224 209]
  [216 223 208]
  ...
  [170 149  91]
  [167 145  87]
  [166 144  86]]

 [[219 223 211]
  [219 223 211]
  [218 222 210]
  ...
  [169 148  90]
  [168 146  89]
  [167 145  87]]

 [[219 223 211]
  [219 223 211]
  [218 222 210]
  ...
  [170 149  91]
  [169 148  90]
  [169 148  90]]]
[[[146 142 149]
  [107 102 110]
  [ 87  84  94]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[191 186 193]
  [130 125 133]
  [ 95  92 102]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[226 227 224]
  [189 189 187]
  [137 136 141]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[222 223 205]
  [222 223 205]
  [223 225 206]
  ..

[[[167 163 170]
  [141 136 143]
  [ 79  77  95]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[197 192 199]
  [164 159 167]
  [109 107 126]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[221 222 220]
  [193 194 192]
  [145 143 155]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[219 224 209]
  [218 223 208]
  [219 222 205]
  ...
  [169 150  85]
  [166 149  85]
  [162 145  82]]

 [[220 223 207]
  [219 222 205]
  [219 222 205]
  ...
  [171 153  86]
  [168 152  86]
  [165 148  83]]

 [[217 221 204]
  [217 221 204]
  [217 221 204]
  ...
  [174 156  88]
  [171 154  88]
  [167 150  85]]]
[[[154 145 144]
  [130 122 121]
  [102  94  95]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[185 176 175]
  [154 145 144]
  [107 100 101]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[213 207 199]
  [190 183 175]
  [143 138 134]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[215 225 208]
  [216 227 209]
  [216 227 209]
  ..

[[[149 146 148]
  [118 115 118]
  [ 83  81  93]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[183 179 182]
  [134 130 133]
  [104 102 114]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[223 222 218]
  [192 191 187]
  [139 137 142]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[223 218 199]
  [224 220 200]
  [224 220 200]
  ...
  [173 160  91]
  [170 158  92]
  [169 157  91]]

 [[224 219 201]
  [226 220 203]
  [226 220 203]
  ...
  [175 159  91]
  [174 159  96]
  [173 158  95]]

 [[224 219 201]
  [226 220 203]
  [226 220 203]
  ...
  [174 158  90]
  [172 157  93]
  [172 157  93]]]
[[[172 172 172]
  [129 129 129]
  [ 91  92  96]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[213 213 213]
  [178 178 178]
  [142 143 148]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[234 238 233]
  [219 223 218]
  [193 193 193]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[219 222 205]
  [217 221 204]
  [216 220 203]
  ..

[[[178 177 181]
  [154 152 157]
  [117 112 120]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[208 207 212]
  [189 187 192]
  [150 145 153]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[221 226 223]
  [202 208 205]
  [181 177 183]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[217 221 204]
  [217 221 204]
  [219 222 205]
  ...
  [170 151  86]
  [168 151  88]
  [167 150  86]]

 [[219 220 204]
  [221 222 205]
  [221 222 205]
  ...
  [169 149  86]
  [167 149  88]
  [167 149  88]]

 [[219 220 204]
  [219 220 204]
  [219 220 204]
  ...
  [167 147  84]
  [165 147  86]
  [165 147  86]]]
[[[195 193 177]
  [155 154 138]
  [ 95  91  96]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[210 208 193]
  [176 175 159]
  [128 124 129]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[221 225 199]
  [197 201 176]
  [168 166 152]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[217 218 195]
  [215 215 192]
  [213 214 191]
  ..

[[[187 187 189]
  [171 170 173]
  [128 125 134]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[205 204 207]
  [191 190 193]
  [167 163 173]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[218 222 217]
  [202 206 201]
  [184 186 188]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[223 224 208]
  [222 223 207]
  [222 223 207]
  ...
  [175 157  89]
  [173 156  91]
  [171 154  88]]

 [[219 222 205]
  [219 222 205]
  [219 222 205]
  ...
  [176 158  83]
  [176 157  85]
  [173 154  82]]

 [[217 221 204]
  [217 221 204]
  [219 222 205]
  ...
  [175 156  82]
  [175 156  84]
  [172 153  81]]]
[[[186 180 183]
  [138 132 136]
  [ 98  88  98]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[212 207 210]
  [176 171 174]
  [124 113 124]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[226 228 223]
  [205 207 202]
  [162 155 156]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[219 222 205]
  [216 220 203]
  [216 220 201]
  ..

[[[144 149 148]
  [116 121 120]
  [ 85  89  97]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[182 187 186]
  [150 155 154]
  [116 120 129]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[210 223 210]
  [185 199 185]
  [151 158 157]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[222 224 203]
  [221 223 202]
  [219 222 201]
  ...
  [170 153  83]
  [168 151  81]
  [163 146  76]]

 [[219 222 201]
  [219 222 201]
  [219 222 201]
  ...
  [172 153  83]
  [167 150  85]
  [165 148  83]]

 [[218 221 200]
  [219 222 201]
  [218 221 200]
  ...
  [173 154  84]
  [168 152  86]
  [166 149  84]]]
[[[145 137 140]
  [107  99 103]
  [100  90 101]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[171 163 167]
  [120 112 116]
  [112 102 112]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[211 205 203]
  [194 187 186]
  [161 152 158]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[214 223 210]
  [214 223 210]
  [213 221 209]
  ..

[[[141 138 139]
  [101  99  99]
  [ 73  67  77]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[172 170 170]
  [144 142 142]
  [ 96  91 101]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[199 207 196]
  [174 182 172]
  [141 137 142]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[200 205 191]
  [200 205 191]
  [200 204 192]
  ...
  [149 134  59]
  [144 132  59]
  [141 129  56]]

 [[202 205 191]
  [202 205 191]
  [202 205 191]
  ...
  [148 134  63]
  [144 133  65]
  [142 131  62]]

 [[202 205 191]
  [201 204 190]
  [201 204 190]
  ...
  [151 136  65]
  [147 136  67]
  [144 133  65]]]
[[[141 137 140]
  [ 78  74  77]
  [ 62  57  71]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[191 187 190]
  [136 133 136]
  [ 91  86 100]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[208 210 205]
  [190 191 187]
  [144 142 149]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[201 204 197]
  [201 204 197]
  [203 205 198]
  ..

[[[164 157 151]
  [151 144 138]
  [127 120 114]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[210 202 197]
  [184 177 171]
  [137 130 124]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[243 240 234]
  [217 215 208]
  [179 176 171]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[230 234 215]
  [231 236 217]
  [231 235 218]
  ...
  [183 168 102]
  [179 166 104]
  [177 164 102]]

 [[229 236 217]
  [229 236 217]
  [231 236 219]
  ...
  [185 170  99]
  [181 167 101]
  [178 164  98]]

 [[229 236 217]
  [229 236 217]
  [229 235 218]
  ...
  [185 170  99]
  [180 166 100]
  [178 164  98]]]
[[[183 176 177]
  [148 141 142]
  [104  92  99]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[204 197 198]
  [173 165 167]
  [144 133 139]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[232 229 225]
  [199 195 191]
  [178 170 174]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[235 235 219]
  [235 235 219]
  [235 235 219]
  ..

[[[220 216 208]
  [183 179 171]
  [138 127 138]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[251 247 238]
  [220 216 208]
  [183 173 183]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 247]
  [249 250 240]
  [220 213 207]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 239]
  [255 255 239]
  [254 255 238]
  ...
  [207 193 114]
  [204 192 114]
  [200 187 109]]

 [[255 255 240]
  [254 255 239]
  [254 255 238]
  ...
  [205 193 115]
  [203 192 119]
  [199 187 114]]

 [[254 255 239]
  [254 255 239]
  [253 255 236]
  ...
  [204 192 114]
  [202 191 117]
  [199 187 114]]]
[[[217 216 214]
  [171 169 167]
  [116 117 126]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[241 239 237]
  [216 215 213]
  [158 159 168]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 252]
  [242 244 239]
  [213 214 212]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[247 255 236]
  [247 255 236]
  [249 255 236]
  ..