In [1]:
import tensorflow as tf 
import numpy as np
import pickle
import cv2

CATEGORIES = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q' ,'R' , 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'del', 'nothing', 'space']
model = tf.keras.models.load_model('/Users/ishan/Desktop/Deep Learning/Trained models/ASL_image_classifier')
img = "/Users/ishan/Desktop/dataset/ASL/alfa_test/K_test.jpg"
img = cv2.imread(img,cv2.IMREAD_GRAYSCALE)
print(img)

[[ 27  33  26 ...  31  27  29]
 [ 30  28  30 ...  27  33  27]
 [ 29  30  90 ...  71  68  31]
 ...
 [ 29  27  26 ... 113 119  26]
 [ 31  28  25 ... 116 112  30]
 [ 28  28  30 ...  29  28  30]]


In [4]:
img = img.astype(float)

''''img = cv2.resize(img,(50,50))'''

img = np.reshape(img,(1,50,50,1))
print(img)

[[[[ 44.5 ]
   [ 61.25]
   [ 60.5 ]
   ...
   [ 42.5 ]
   [ 46.75]
   [ 49.75]]

  [[ 75.  ]
   [115.75]
   [107.5 ]
   ...
   [ 47.5 ]
   [ 42.  ]
   [ 39.5 ]]

  [[ 96.25]
   [161.  ]
   [159.25]
   ...
   [ 56.5 ]
   [ 55.25]
   [ 58.75]]

  ...

  [[ 71.  ]
   [ 63.  ]
   [ 32.5 ]
   ...
   [114.  ]
   [114.  ]
   [114.  ]]

  [[ 34.25]
   [ 40.75]
   [ 38.75]
   ...
   [115.  ]
   [115.25]
   [114.  ]]

  [[ 26.5 ]
   [ 15.25]
   [ 13.5 ]
   ...
   [114.  ]
   [114.5 ]
   [115.  ]]]]
